# Five Tensor Functions using Pytorch

Like vectors and matrices, tensors can be represented in Python using the N-dimensional array (ndarray). Tensors use matrix to represent. It makes it so much easy to represent information in an array. Here are five tensor functions:

- torch.eye()
- torch.unbind()
- torch.take()
- torch.clone()
- torch.polar()

Before we begin, let's install and import PyTorch

In [15]:
# Import torch and other required modules
import torch

## Function 1 - torch.eye()

Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [16]:
# Example 1 

num = torch.eye(n=3, m=4)
num

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

The above code was used to create a tensor which was diagonal with values being ones and zeros

In [17]:
# Example 2 

num = torch.eye(n=7)
num

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

The above code shows output of an nxn tensor due to the fact that we specified n only and not nxm

In [18]:
# Example 3 - breaking (to illustrate when it breaks)

num1 = torch.eye(n=10, m=2.5)

num1

TypeError: ignored

The above example throws an error beacause a float value was passed in the .eye function argument.

Therefore, it is important that we remember to always pass an integer value the .eye argument when palcing values for n or m

This is used when we want to create a diagonal tensor

Let's save our work using Jovian before continuing.

In [19]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [20]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/dinmdohan813/01-tensor-operations


'https://jovian.ai/dinmdohan813/01-tensor-operations'

## Function 2 - torch.unbind()

This function removes a tensor dimension along the given dimension dim The default dimension is 0 i.e. dim=0



In [22]:
# Example 1 -

num1 = torch.tensor([[2, 4, 6],
                  [8, 10, 12]])

print(num1)
num2 = torch.unbind(num1)
num2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


(tensor([2, 4, 6]), tensor([ 8, 10, 12]))

The above example shows two ouput:

- Which is the output of num1
- The second ouput which is the output for num2. Now from the output, we can see that torch.unbind is used to remove the dimension of a tensor.

In [23]:
# Example 2 

num1 = torch.tensor([[[2, 4, 6],
                  [8, 10, 12]],
                  [[10, 20, 30],
                  [40, 50, 60]]])

print(num1.shape)
num2 = torch.unbind(num1, dim=2)
num2

torch.Size([2, 2, 3])


(tensor([[ 2,  8],
         [10, 40]]), tensor([[ 4, 10],
         [20, 50]]), tensor([[ 6, 12],
         [30, 60]]))

The above example has num1 having a shape of 2 x 2 x 3.

Now, using the unbind function and giving dimension to be 2 has unbinded the tensor values into a 2 seperate tensor.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)

num1 = torch.tensor([[[2, 4, 6],
                  [8, 10, 12]],
                  [[10, 20, 30],
                  [40, 50, 60]]])

print(num1)
num2 = torch.unbind(num1, dim=3)
num2

tensor([[[ 2,  4,  6],
         [ 8, 10, 12]],

        [[10, 20, 30],
         [40, 50, 60]]])


IndexError: ignored

The above example outputs an IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3) error. Meaning the dimension value 3 specified is not in line with the dimension of num1.

This function is used whenever we want to remove the dimension of a tensor.

Closing comments about when to use this function

In [26]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/dinmdohan813/01-tensor-operations


'https://jovian.ai/dinmdohan813/01-tensor-operations'

## Function 3 - torch.take()

Returns a tensor with the elements of the input tensors at the given indices. The input tensor is treated as a 1D tensor to return the values.

In [33]:
# Example 1 -

num1 = torch.tensor([10, 20, 30, 40, 50])

num2 = torch.take(num1, torch.tensor([-1]))

num2

tensor([50])

The above code had num1 taking in a 1D tensor value.

num2 was given a value from the list of values in num1 and this was made possible by indexing (-1).

In [34]:
# Example 2 

num1 = torch.tensor([[10, 20, 30, 40, 50],
                     [60, 70, 80, 90, 100]])

num2 = torch.take(num1, torch.tensor([-1,-4]))

num2

tensor([100,  70])

The above example also shows a 2D tensor in num1.

num2 was also giving a value from the tensor values as seen in num1.

Now, the indexing was done from the back counting from -1 to -4.

In [35]:
# Example 3 - breaking (to illustrate when it breaks)

num1 = torch.tensor([[10, 20, 30, 40, 50],
                     [60, 70, 80, 90, 100]])

num2 = torch.take(num1)

num2

TypeError: ignored

The above code throws an Error: TypeError: take() missing 1 required positional arguments: "index"

Which signifies that an argument was missing and that argument was an index of value num1.

This function is used when we want a specific value from a list of values in a tensor.

In [36]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/dinmdohan813/01-tensor-operations


'https://jovian.ai/dinmdohan813/01-tensor-operations'

## Function 4 - torch.clone()

Some explanations torch.Tensor.clone returns a copy of the tensor with the same size and data type.

When we create a copy of the tensor using x=y , changing one variable also affects the other variable since it points to the same memory location.

In [29]:
# Example 1 
num1 = torch.tensor([[5., 10.],
                  [15., 20.],
                  [25., 30.]])
print('num1 values:', num1)
num2 = num1
num1[2,1]=2
print('num2 values', num2)

num1 values: tensor([[ 5., 10.],
        [15., 20.],
        [25., 30.]])
num2 values tensor([[ 5., 10.],
        [15., 20.],
        [25.,  2.]])


The above code has a variable by name (num1) with a 3 x 2 shape.

num2 was given the value of num1 when we used the Equality = sign (num2 = num1).

After which, a value was changed in num1 via indexing to a value of 2. But due to the fact that num2 was given the values of num1, the change in num1 was outputed in num2.

In [30]:
# Example 2 

num1 = torch.tensor([[5., 10.],
                  [15., 20.],
                  [25., 30.]])
print('num1 values:', num1)

num2 = num1.clone()
num1[2,1]=2
print('num2 values', num2)

num1 values: tensor([[ 5., 10.],
        [15., 20.],
        [25., 30.]])
num2 values tensor([[ 5., 10.],
        [15., 20.],
        [25., 30.]])


From our second example, you can see that using .clone() to give value to num2 made it possible to retain the deepcopy of our previous tensor of (num1) even after making changes to it.

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
num1 = torch.tensor([[5., 10.],
                  [15., 20.],
                  [25., 30.]])
print('num1 values:', num1)
num2 = num1.clone
num1[2,1]=2
print('num2 values', num2)

num1 values: tensor([[ 5., 10.],
        [15., 20.],
        [25., 30.]])
num2 values <built-in method clone of Tensor object at 0x7fb154b50a00>


We could not get the value nor output of num2 even after giving it same values as seen in num1 due to the fact that the parenthesis was omitted.

Therefore, it is paramount to always add the parenthesis at the end of the clone function.

Always add the parenthesis at the end of the clone command (Do .clone() and not .clone)

This function is used when we want a value of a variable to be exact value with another variable irrespective of whatever change that may occur on the cloned variable.

Let's save our work using Jovian before continuing.

In [32]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/dinmdohan813/01-tensor-operations


'https://jovian.ai/dinmdohan813/01-tensor-operations'

## Function 5 - torch.rand()

The rand functions come in a number of flavours we have the rand() ,randn() and the randint(). Basically this function gives you a tensor of random numbers

In [37]:
# We start with the rand()function
tens1=torch.rand(4,3)
tens1

tensor([[0.2619, 0.8590, 0.1870],
        [0.7463, 0.7283, 0.9087],
        [0.8312, 0.2541, 0.8936],
        [0.3101, 0.1543, 0.0027]])

This fuction is given the number of rows and columns then it will give you random numbers from a uniform distribution of the interval between 0(inclusive) and 1(exclusive). In our example we have a 4 x 3 tensor.

In [38]:
# We look at the randint()fuction
tens2=torch.randint(3,19,(4,3))
print(tens2)

tensor([[14,  8, 13],
        [11, 16, 11],
        [ 4,  7,  9],
        [ 5, 10, 17]])


This gives us a random distribution of integers. You pass to it torch.randint(start,end,(rows,columns)) these are integers whilst the oter gives us the floats.

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
tens3=torch.randint(2.,15,(4,4))
tens

TypeError: ignored

The operation failed because the randint() can only take integers in the example I passed a floatto the start so it could not work

The rand() function is a very interesting and useful function as we are going to see in this notebook we are going to use it alot as we go.

In [ ]:
jovian.commit(project='01-tensor-operations')

.

.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
